apiVersion: operator.tigera.io/v1
kind: Goldmane
metadata:
  name: default
---
apiVersion: operator.tigera.io/v1
kind: Whisker
metadata:
  name: default
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-all-demo
  namespace: default
spec:
  order: 10
  tier: default
  selector: all()
  types:
  - Ingress
  - Egress
  ingress:
  - action: Allow
  egress:
  - action: Allow
