apiVersion: v1
kind: Secret
metadata:
  name: velero-minio-creds
  namespace: proactive-maintenance
stringData:
  cloud: |
    [default]
    aws_access_key_id = minio-admin
    aws_secret_access_key = minio-password
