#!/bin/bash
set -e

# ==============================================================================
# Script: generate_ssot_from_bcm.sh
# description: Principal Engineering Tool to import Legacy BCM Configurations
#              and generate Modern Kubernetes GitOps Overlays (SSOT).
# Maintainer: Platform Engineering Team
# Usage: ./generate_ssot_from_bcm.sh --source <bcm_export.json>
# ==============================================================================

# Colors for "Polished" UX
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Default values
SOURCE_FILE=""
OUTPUT_BASE_DIR="./generated_overlays"
ENVIRONMENTS=("dev" "staging" "prod-az1" "prod-az2")

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

print_banner() {
    echo -e "${BLUE}"
    echo "    ____  CM  ->  K8S  SSOT  MIGRATOR    "
    echo "   / __ )/ ____/  |  / / /_  __/ __ \    "
    echo "  / __  / /      /| / / / / / / / / /    "
    echo " / /_/ / /___   / |/ / / / / / /_/ /     "
    echo "/_____/\____/  /_/  /_/ /_/  \____/      "
    echo -e "${NC}"
    echo "Initializing Single Source of Truth generator..."
    echo "------------------------------------------------"
}

usage() {
    echo "Usage: $0 --source <path_to_bcm_export.json> [--output <output_dir>]"
    exit 1
}

parse_args() {
    while [[ "$#" -gt 0 ]]; do
        case $1 in
            --source) SOURCE_FILE="$2"; shift ;;
            --output) OUTPUT_BASE_DIR="$2"; shift ;;
            *) usage ;;
        esac
        shift
    done

    if [[ -z "$SOURCE_FILE" ]]; then
        log_error "Source file is required."
        usage
    fi
}

validate_source() {
    log_info "Validating BCM Source file: $SOURCE_FILE"
    if [[ ! -f "$SOURCE_FILE" ]]; then
        log_error "File not found: $SOURCE_FILE"
        exit 1
    fi
    # In a real scenario, we would validate JSON schema here using `jq`
    log_success "Source file is valid."
}

generate_header() {
    local env=$1
    cat <<EOF
# ==============================================================================
# SINGLE SOURCE OF TRUTH (SSOT) - AUTO GENERATED
# Environment: $env
# Source: BCM Export ($SOURCE_FILE)
# Generated At: $(date)
# 
# DO NOT EDIT THIS FILE MANUALLY IF "BCM_LOCK" IS TRUE.
# ==============================================================================
EOF
}

extract_config() {
    local env=$1
    local key=$2
    # Mocking extraction. In real life: jq -r ".environments.$env.$key" "$SOURCE_FILE"
    # Here we simulate logic based on environment
    case $env in
        dev)
            if [[ "$key" == "replicaCount" ]]; then echo "1"; fi
            if [[ "$key" == "logLevel" ]]; then echo "DEBUG"; fi
            ;;
        staging)
            if [[ "$key" == "replicaCount" ]]; then echo "2"; fi
            if [[ "$key" == "logLevel" ]]; then echo "INFO"; fi
            ;;
        prod-az1)
            if [[ "$key" == "replicaCount" ]]; then echo "5"; fi
            if [[ "$key" == "logLevel" ]]; then echo "WARN"; fi
            ;;
        prod-az2)
            if [[ "$key" == "replicaCount" ]]; then echo "5"; fi
            if [[ "$key" == "logLevel" ]]; then echo "WARN"; fi
            ;;
    esac
}

process_environment() {
    local env=$1
    local out_dir="$OUTPUT_BASE_DIR/$env"
    mkdir -p "$out_dir"
    local out_file="$out_dir/values-uber-bundle.yaml"

    log_info "Processing environment: $env"
    
    generate_header "$env" > "$out_file"

    local replicas=$(extract_config "$env" "replicaCount")
    local logx=$(extract_config "$env" "logLevel")

    # Generating the YAML structure dynamically
    cat <<EOF >> "$out_file"

global:
  environment: "$env"
  region: "$(echo $env | cut -d'-' -f2)"

# ------------------------------------------------------------------------------
# APP CONFIGURATION
# ------------------------------------------------------------------------------
app-core:
  replicaCount: $replicas
  image:
    repository: registry.internal.corp/core-app
    tag: "$(date +%Y.%m).0-bcm-import"
  logging:
    level: "$logx"

# ------------------------------------------------------------------------------
# NETWORK CONFIGURATION (BCM HOST MAPS)
# ------------------------------------------------------------------------------
network:
  ingress:
    enabled: true
    hosts:
      - host: $env.api.internal.corp
        paths: ["/"]

# ------------------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------------------
redis:
  architecture: "standalone" # BCM default
  auth:
    enabled: true
    # Secret references should be injected via ExternalSecretStore, avoiding plain text here
    existingSecret: "$env-redis-auth"

EOF
    log_success "Generated SSOT Overlay: $out_file"
}

main() {
    print_banner
    parse_args "$@"
    validate_source

    log_info "Starting migration of Manual Configs to Kubernetes Overlays..."
    
    for env in "${ENVIRONMENTS[@]}"; do
        process_environment "$env"
    done

    echo "------------------------------------------------"
    log_success "Migration Complete."
    log_info "Next Steps:"
    echo "1. Review generated YAMLs in $OUTPUT_BASE_DIR"
    echo "2. Commit to Git to establish Initial SSOT"
    echo "3. Point ArgoCD to $OUTPUT_BASE_DIR/\$ENV"
    echo "------------------------------------------------"
}

# Run Main
main "$@"
